### ISSUE TITLE
Bug Report: missing values not recognized after pandas convert_dtypes()

### ISSUE THREAD

**Issue by baptiste-pasquierQB** [ydataai/ydata-profiling#1431]
### Current Behaviour

After applying `convert_dtypes()` method from pandas, ydata profiling no longer recognizes missing values (pd.NA).

### Expected Behaviour

After applying `convert_dtypes()`, the profiling report should recognize missing values.``

### Data Description

df = pd.DataFrame(
    {
        "feature_1": [1, 2, 3],
        "feature_2": [1, 2, None],
        "feature_3": [1.1, 2.1, None],
        "feature_4": [1, 2, np.nan],
        "feature_5": [1.1, 2.1, np.nan],
        "feature_6": [1, 2, pd.NA],
        "feature_7": [1.1, 2.1, pd.NA],
    }
)

### Code that reproduces the bug

```Python
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport

df = pd.DataFrame(
    {
        "feature_1": [1, 2, 3],
        "feature_2": [1, 2, None],
        "feature_3": [1.1, 2.1, None],
        "feature_4": [1, 2, np.nan],
        "feature_5": [1.1, 2.1, np.nan],
        "feature_6": [1, 2, pd.NA],
        "feature_7": [1.1, 2.1, pd.NA],
    }
)

profile = ProfileReport(df, title="Valid report")
profile.to_file("valid_report.html")

df = df.convert_dtypes()

profile = ProfileReport(df, title="Bug Report")
profile.to_file("bug_report.html")
```

### pandas-profiling version

4.5.1

### Dependencies

```Text
numpy==1.23.5
pandas==2.0.3
ydata-profiling==4.5.1
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by aquemy** [comment]
Hey @baptiste-pasquierQB ,

This is known issue related to the fact that we have a limited support for Pandas 2.0 new types:

Without `convert_dtypes`:
```
feature_1      int64
feature_2    float64
feature_3    float64
feature_4    float64
feature_5    float64
feature_6     object
feature_7     object
dtype: object
```

With `convert_dtypes`:
```
feature_1      Int64
feature_2      Int64
feature_3    Float64
feature_4      Int64
feature_5    Float64
feature_6     object
feature_7     object
dtype: object
```

The datatypes with a capital letter are super seeding the original ones, in particular to improve how missing values are handled.

The problem is that by default, pandas 2.0 will still infer with the old types for backward compatibility.
We are looking for a solution to handle them properly but we need to be careful because the type inference is really at the heart of `ydata-profiling` and we don't want to introduce regression here as it would affect all our users.
