### ISSUE TITLE
data description not rendering line breaks in html output

### ISSUE THREAD

**Issue by pandichef** [ydataai/ydata-profiling#1437]
### Current Behaviour

The dataset description field as documented [here](https://ydata-profiling.ydata.ai/docs/master/pages/use_cases/metadata.html) doesn't render line breaks correctly.  For example, "line1\nline2" is shown as "line1line2" in the html report.

### Expected Behaviour

Handle line breaks correctly in the html output.

### Data Description

For example,
```
from sklearn import datasets
report = df.profile_report(
    dataset={"description": datasets.load_iris().DESCR}, # DESCR contains line breaks
)
```

### pandas-profiling version

N/A

### Dependencies

```Text
N/A
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by alexbarros** [comment]
There were two issues at play here one is a configuration issue, removing line breaks is a known side effect of `minify_html`, so turning it off would solve the problem, if not for the second issue. Which was the HTML template was ignoring the description format, this was fixed by #1462.
You can disable the `minify_html` through the config file or updating the `Settings` of the `ProfileReport`, e.g.

```
config.yaml
html:
    minify_html: false

python
report = ProfileReport(df, config_file='config.yaml')
```

```
report = ProfileReport(df)
report.config.html.minify_html = False
```
