### ISSUE TITLE
Unable to run the pandas profiling

### ISSUE THREAD

**Issue by kpn25** [ydataai/ydata-profiling#1623]
C:\Ananconda4\Lib\site-packages\ydata_profiling\model\correlations.py:66: UserWarning: There was an attempt to calculate the auto correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"auto": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: 'Phillipines'')
  warnings.warn(

**Comment by fabclmnt** [comment]
Hi @kpn25 ,

this is a duplicated issue from https://github.com/ydataai/ydata-profiling/issues/1527. The fix will be released with the next release. 

Also, please make sure to follow the community guidelines. Before opening a new issue make sure that is not already reported by another user : https://docs.profiling.ydata.ai/latest/support-contribution/help_troubleshoot/

Last but not the least, make sure to follow the required inputs from the issue templates, so we can have access to all the information that we need in order to reproduce your issue.
